### ISSUE TITLE
Sementes 

### ISSUE THREAD

**Issue by Felipehot** [DorkmasterFlek/smrpg_web_randomizer#100]
PLEASE DO NOT USE THIS FORM TO REQUEST FEATURES!  THIS IS FOR BUG REPORTS ONLY!
If you wish to discuss new features, please join our Discord server: http://discord.smrpgspeedruns.com

Console or Emulator: 

 If emulator state which emulator and version.  If console, state which flash cart firmware.

Were you using Crowd Control:

 NOTE: Crowd Control is NOT officially supported for the randomizer currently.  Please ONLY report issues if they are happening WITHOUT Crowd Control!  See https://forum.warp.world/t/super-mario-rpg-legend-of-the-seven-stars-snes/14219 for details.

Flags (paste flag string if available): 

Seed number or hash (seed number or hash string from filename or download page): 
OR
Permalink (permalink URL from download page if you have it): 

Description of problem: 
Tá dando erro na criação de sementes

**Comment by DorkmasterFlek** [comment]
I'm not seeing any error when generating a seed...  I just upgraded the web server, but it doesn't seem to be related to that.  What error message did you see exactly?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/45515587/235236145-b78a9302-5de1-4cde-b2ab-307f082ab4cc.png)
trying right now, getting this, imagine being same issue
tried typing into the seed field, clicking download either showed the same error or did nothing
rom was uploaded, known to be right one as i used it in the past
tried anonymous tab and clearing cache
browser is chrome, has adblock and other scripting extensions but nothing that should break the site
tried firefox as well


flags: Ks R7k Cspjl -nfc Tb3kd $ M2 Sb3 Edfsa Bc Qsba X2 P1 Nbmq Gm -fakeout D4s 
advanced also failed

FIX: Disabling flag Es solved it

**Comment by DorkmasterFlek** [comment]
Ah, yes we figured out the Es flag in particular was causing it in the Discord.  This turned out to be an issue with the recent web server upgrade which moved Python from 3.10 to 3.11 and there was a change to random sampling there.  This flag should be fixed again, apologies!
