### ISSUE TITLE
Key item(s) locked behind failed Booster Tower Curtain Game

### ISSUE THREAD

**Issue by treydeal** [DorkmasterFlek/smrpg_web_randomizer#101]
Console or Emulator: Emulator - Beetle Supafaust v1.29.0

Were you using Crowd Control: No

Flags (paste flag string if available): Ksb R7 Cspjl -nfc -palette Tc4mk M2 Sc4 Edfsa Bm Qsba X3 Nm -fakeout D2s W -showequips

Seed number or hash (seed number or hash string from filename or download page): 1160058858
OR
Permalink (permalink URL from download page if you have it): https://randomizer.smrpgspeedruns.com/h/5eb4694e482009951c6857323e64e8b5

Description of problem: I got to a point where I had checked absolutely every location I knew to check to find Castle Key 1, and could not figure out where it could be. I checked the spoiler log, and this seed has [BoosterTowerCurtainGame: "CastleKey1"], which I have gotten into the habit of failing on purpose for the sake of time, thinking this was surely marked missable - but it does not appear to be. Also blocked behind this is the Big Boo Flag: I can't get through Castle Key 1's door to do Castle Key 2's fights, to get to the Fertilizer location.

**Comment by DorkmasterFlek** [comment]
Yup, that location should be marked missable.  I just pushed an update to fix that, thanks!
