### ISSUE TITLE
Connection not secure

### ISSUE THREAD

**Issue by SmashManiac** [DorkmasterFlek/smrpg_web_randomizer#20]
randomizer.smrpgspeedruns.com does not support HTTPS.

This causes the following issues:
- Browser warnings. (For example, in Chrome, "Not Secure" appears in the URL bar.)
- Vulnerable to man-in-the-middle attacks to deface the website with ads or inject malware.
- Cannot use HTTP/2 for better performance.

Note: Some CAs can automatically offer and renew TLS certificates for free nowadays, so budget should not be an issue.

**Comment by DorkmasterFlek** [comment]
Plan to implement HTTPS redirect for the entire site in the next couple days.

**Comment by DorkmasterFlek** [comment]
HTTPS redirect added to web server config using LetsEncrypt.
