### ISSUE TITLE
Hurly Gloves without Mario in the party + Come Back = softlock?

### ISSUE THREAD

**Issue by DorkmasterFlek** [DorkmasterFlek/smrpg_web_randomizer#21]
https://www.twitch.tv/videos/306476357

This was a softlock plus it actually erased the save file, which is really surprising...

Peach had Hurly Gloves, but Mario was not in the party.  This caused the character in position 1 (Mallow) to become glitched out.  When Peach used Come Back, it softlocked and erased the save file.

NOTE: This was being played on a SNES Classic, so that may have something to do with the save file being erased.  We don't know how the SRAM is handled in that, and nobody else has played a randomizer seed on it.

**Comment by DorkmasterFlek** [comment]
Unable to reproduce this myself so far.  Additional info from Alanim, there is apparently a super rare hard crash on Megasmilax that can delete all saves.  Checkers ran into this years ago while throwing an ice bomb at it.

This may not be a SNES Classic issue specifically, but it does appear to be something that is most likely very rare/difficult to reproduce.

**Comment by hellstja** [comment]
I had this happen to me today (3/2/19) against Valentina and Dodo. Save file deleted.

SNES 9x v1.56
Flags: Ks R7k Cspjl Edfsa B S Qsba P1 Gm

**Comment by DorkmasterFlek** [comment]
That might happen if Mario is in the middle slot and gets taken away by Dodo.  Looking at the animation code to see if we can make it just always throw the doll instead...

**Comment by DorkmasterFlek** [comment]
Managed to figure out the Hurly Gloves animation script to make the game think Mario is dead and use the doll all the time.  Side effect of this change is Mario is able to use the Hurly Gloves without softlocking now!
