### ISSUE TITLE
path to bowser's keep not open

### ISSUE THREAD

**Issue by ramh2001** [DorkmasterFlek/smrpg_web_randomizer#26]
Using open mode, i received the 6th star in Culex's spot (hammer bros for my rng) but the path to Bowser's keep did not open. I tried talking to Mallow's parents to open the bus and the cut scene played, but when i go to board, nothing happened. The 6th star was literally the last boss i had left standing previous to the keep

**Comment by DorkmasterFlek** [comment]
Can you please tell us how you were playing?  Console, emulator, version of emulator/firmware, etc.  Seed number and/or hash would be very helpful as well.

**Comment by DorkmasterFlek** [comment]
I'm unable to reproduce this.  BK opened fine after getting 6 stars with the last one on Culex in a test seed.  Are you sure you didn't have the 7 star flag enabled?

**Comment by DorkmasterFlek** [comment]
Have not received any further info on this, and there's been multiple updates with hundreds of seeds generated without issue.
