### ISSUE TITLE
Belome 1

### ISSUE THREAD

**Issue by hellstja** [DorkmasterFlek/smrpg_web_randomizer#27]
Console or Emulator: Emulator

 If emulator state which emulator and version.  If console, state which flash cart firmware.
SNES 9x v1.56

Flags (paste flag string if available):  Ks R7k Cspjl Edfsa B S Qsba P1 Gm
Filename: SMRPG_US_8.0beta11_open_40d80ca69feed97625aebebebe8496fd_3564929670
Save filenames: Muckle JOhnny Leuko Dodo

Description of problem:
Belome 1 will try to eat characters causing a softlock.

Two different cases happen that I could reproduce: 1. Belome 1 does the Belome 1 script and eats the character in the third slot, then will eat another character and try to produce a clone like Belome 2. Game immediately softlocks (was able to soft reset). 2. He does not do the Belome 1 script and immediately does the Belome 2 script, attempting to eat a character and produce a clone. Regardless of what character is eaten, the third party member disappears and upon release, a glitched character portrait appears in slot 3 and no member exists in the party. If the turn order comes to #3, the game soft locks as there's no actable member. Since this is in the Jinx 2 fight location, I was able to run. Soft-reset also available. (see attached screenshot)

![belome 1 bug](https://user-images.githubusercontent.com/260891/53689184-a5108e80-3d04-11e9-960d-716907856f11.png)

**Comment by DorkmasterFlek** [comment]
This is an issue with Belome 1 accidentally jumping to Belome 2's battle script.  We've got a new patch in the works that should fix this soon...

**Comment by DorkmasterFlek** [comment]
This should be fixed in the new beta patch that just went live.
