### ISSUE TITLE
Custom game with "Character Spell Lists" option disabled starts characters without their first spell

### ISSUE THREAD

**Issue by bancroft87** [DorkmasterFlek/smrpg_web_randomizer#28]
Console or Emulator: emulator- snes9x v1.53

 If emulator state which emulator and version.  If console, state which flash cart firmware.

Flags (paste flag string if available): 

Description of problem: When creating a custom randomization game without the characters' spells randomized, Mario begins without the Jump spell; in the one game I've gone as far as the second character, Mallow didn't have the Thunderbolt spell, either. Both characters gain their second spell at the appropriate level, but still missing the first.

**Comment by DorkmasterFlek** [comment]
This is an issue with the old version 7.  Current beta version 8 has this fixed, among numerous other things.

https://randomizer-beta.smrpgspeedruns.com/
