### ISSUE TITLE
Mushroom Way Randomized Chest Refills when Re-entering

### ISSUE THREAD

**Issue by gokiburikin** [DorkmasterFlek/smrpg_web_randomizer#49]
Emulator: Snes9x Snes9x v1.59.2 for Windows.

Flags (paste flag string if available): Ks R7k Cspjl -palette Tc4k M2 Sb4 Edfsa! Bmc Qsba! X3 -noexp P1 Nbm Gsmke -fakeout D1s

Description of problem: The chest in Mushroom Way which usually contains a healing mushroom can be randomized and resets back to full when you re-enter the area. I don't know if this behaviour is normal for the base game, but you can get as many of whatever appears in there in the randomizer as you want.

**Comment by DorkmasterFlek** [comment]
This is fixed in the most recent update.
