### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by hamtaro1234** [DorkmasterFlek/smrpg_web_randomizer#51]
PLEASE DO NOT USE THIS FORM TO REQUEST FEATURES!  THIS IS FOR BUG REPORTS ONLY!
If you wish to discuss new features, please join our Discord server: http://discord.smrpgspeedruns.com

Console or Emulator: 
zsnesw151-402

 If emulator state which emulator and version.  If console, state which flash cart firmware.

Flags (paste flag string if available): 

Description of problem: Game freezes everytime I try and equip items.

**Comment by DorkmasterFlek** [comment]
ZSNES does not emulate SA-1 games properly (among numerous other inaccuracies with it).  It is HIGHLY recommended not to use ZSNES in general, try one of the suggested emulators on the How To Play section of the website.
