### ISSUE TITLE
Bug Report: Game Locks Up On Equip Screen

### ISSUE THREAD

**Issue by RachelTheSeeker** [DorkmasterFlek/smrpg_web_randomizer#67]
Console or Emulator: ZSNES, latest version for Windows

Flags (paste flag string if available): "K Cj Tb3 Nq Gsmke"; exact seed is "3445590563" if it matters

Description of problem: Played through the seed as normal, getting up to the Bowyer fight and clearing it. Once I got Geno onto my party however, any time I would fuss around in my Equip screen, the game would lock up when going to equip an item. 

The background image scrolled as normal and the music still played, but the game wouldn't accept button commands and any selection effects (the finger icon, the item name being "lifted") stopped working. I had to re-fight Bowyer and did a save state after obtaining Geno to make sure this wasn't a one-time fluke, and it still locks up in the Equip screen.

Originally I thought the issue would only extend to equipping Geno, but trying to equip a Fuzzy Shirt to Mario I found the exact same problem. Weirdly enough it doesn't trigger exactly each time I try to equip something either, though of note it almost always freezes when I move over to the Ghost Medal I had recently obtained in my save?

On the off chance my footage might help, I was streaming the game on Twitch. The video can be found at https://www.twitch.tv/videos/495262830. The bug begins at about 1:26:41, and carries on for 1:26:53 when I realize the game has frozen. After I beat Bowyer again, I fiddled a bit on stream with the bug in the hopes to create footage for this report, remembering that you folks had that feature. This experimentation carries onward from 1:31:48 to about the rest of the video. Forgive my poor voice volume and quality, this is my first Twitch stream and I can't say my vocal training is the best right now. -_-

**Comment by DorkmasterFlek** [comment]
The problem is ZSNES.  This emulator is no longer actively developed and has a long history of accuracy issues due to various speed hacks it used to run on less powerful hardware.  It does not emulate SA-1 games properly and should generally never be used.  If you're running Windows, the most recommended option is snes9x.  This is easy to set up and use and generally considered the best SNES emulator overall.
