### ISSUE TITLE
Beta crashes on SD2SNES on SuperNT

### ISSUE THREAD

**Issue by oobitydoo** [DorkmasterFlek/smrpg_web_randomizer#75]
PLEASE DO NOT USE THIS FORM TO REQUEST FEATURES!  THIS IS FOR BUG REPORTS ONLY!
If you wish to discuss new features, please join our Discord server: http://discord.smrpgspeedruns.com

Console or Emulator:

 If emulator state which emulator and version.  If console, state which flash cart firmware.

SD2SNES (1.8.0-sa1-v06) on SuperNT

Flags (paste flag string if available): 
Mode: Open
Version: 8.2beta5
Flags: Ks R7kc Cspjl -nfc Yb Zwgt Tc4 Sc4 Edfsac! Bmcs Qsba! X3 Nbmq -fakeout D6s
Seed: 3242283158
https://randomizer-beta.smrpgspeedruns.com/h/2ac6c547d2ba8b29aaab4fb8e14fbe74

Description of problem:
The game softlocks in some battles, with enemies disappearing (not defeated, just disappearing) and music continuing to play but without any input or menus available, which requires a hard reset. Currently, I only have Bowser in my party, and he is in the center battle slot by default. I've specifically had this happen in Kero Sewers at the main boss, in the Marrymore boss fight, and in a regular fight in Booster Tower against a Chomp + Jester

**Comment by oobitydoo** [comment]
I just updated my SD2SNES to firmware 1.10.3 and tested that it still crashes in the same way on the aforementioned Booster Tower fight.

**Comment by DorkmasterFlek** [comment]
That might've been due to the most recent change on the beta branch for the spell shuffle.  I've reverted that for now in a new beta version.
