### ISSUE TITLE
Game freezes when entering room with giant squid after beating it

### ISSUE THREAD

**Issue by Sygos** [DorkmasterFlek/smrpg_web_randomizer#78]
PLEASE DO NOT USE THIS FORM TO REQUEST FEATURES!  THIS IS FOR BUG REPORTS ONLY!
If you wish to discuss new features, please join our Discord server: http://discord.smrpgspeedruns.com

Console or Emulator: snes9x version 1.56.2

 If emulator state which emulator and version.  If console, state which flash cart firmware.

Flags (paste flag string if available): Ks R7 Cspjl -nfc Tc3y $ M1 Sb4 Edfsa! Bs Qsa X2 Nbmq D2s W 

Description of problem: I beat the boss that is usually the giant squid/blooper (this time it was Booster) in the Sunken Ship and went back to the save room where you have to jump on a barrel to hit one of two switches and saved my game. I went back into the room where you fight the giant squid and then the game, while still playing music, froze.

**Comment by DorkmasterFlek** [comment]
Do you have the seed number or the hash string from the filename or download page?  Or possibly just the permalink URL also from the download page?

EDIT: Nevermind, I found it: seed 1225326727

**Comment by DorkmasterFlek** [comment]
Found the permalink: https://randomizer.smrpgspeedruns.com/h/9a612c6e66d2264bfce95e5f6b9725f6

Confirmed this is happening in snes9x 1.60 with a solo character at least, might be related to no free characters if you have less than a full party...

On that note, 1.56 *should* be okay for this game but I would recommend updating to the latest stable snes9x version in the future just to be safe.

**Comment by DorkmasterFlek** [comment]
Okay confirmed it also happens with two characters, but it works fine with a full party so that seems to confirm it's related to the no free characters feature.  We'll try to skip this jumping back down cutscene, that should fix it.

**Comment by DorkmasterFlek** [comment]
Okay I found the cutscene spot and removed it when jumping down after Kalamari is defeated already.  Pushed this live as a hot fix, this should be fixed now!  Thanks for the report, this was supposed to be included with the no free character changes but it got left out somehow.

**Comment by Sygos** [comment]
You're welcome for the report, and thank you for making this awesome randomizer!
