### ISSUE TITLE
Softlocks when a boss uses Blizzard or Flame Wall.

### ISSUE THREAD

**Issue by TheSaltyBlackCat** [DorkmasterFlek/smrpg_web_randomizer#85]
PLEASE DO NOT USE THIS FORM TO REQUEST FEATURES!  THIS IS FOR BUG REPORTS ONLY!
If you wish to discuss new features, please join our Discord server: http://discord.smrpgspeedruns.com

Console or Emulator: BizHawk 2.3.1 (+ Crowd Control)

If emulator state which emulator and version.  If console, state which flash cart firmware.

Flags (paste flag string if available): Ksb Rk Cspjl -nfc -palette Tc4nmsr Sc4 Edfsa B Qsba X2 P1 Nbm -fakeout D2s W

Seed number or hash (seed number or hash string from filename or download page): 
OR
Permalink (permalink URL from download page if you have it): https://randomizer.smrpgspeedruns.com/h/f3d7d09efd76e73c9b572503a71efd7a

Description of problem: On Booster Tower, Mack has access to Flame Wall when all Shy Guys are destroyed. This locks the game whenever the game decides to use it, because the game launches the animation, but never finishes it, which locks the game into the Flame Wall animation. This is also a problem with the Samurai on Seaside Town's mountain, which has access to Blizzard : but instead, the animation never launches, which locks the game into place. The bosses were strong enough to resist multiple attacks, so it was impossible to go through them without getting at least one of those spells.

Although Crowd Control was used to play the seed, no effects were used in those battles to change attacks or to force certain things to happen in battle.

**Comment by DorkmasterFlek** [comment]
I have not heard of any issues with this prior to Crowd Control.  Can you please try without Crowd Control and see if the same situation occurs?  I'm not going to investigate this further unless it happens without CC at this point.  The CC support is not official according to their own FAQ and they have no involvement in the randomizer currently.

https://forum.warp.world/t/super-mario-rpg-legend-of-the-seven-stars-snes/14219

**Comment by TheSaltyBlackCat** [comment]
Just tried right now, the bug was indeed related to Crowd Control somehow tempering with the attack data. Both Seaside Town Mountain's Boomer's Blizzard and Mack's Flame Wall's animation in Booster Tower came out just fine, which leads me to believe there's a problem with the Crowd Control patch instead.

I'll try to forward this to Crowd Control's Team instead, so that they can fix this! Thanks for helping out!

**Comment by DorkmasterFlek** [comment]
Good to know, thank you for checking!
