### ISSUE TITLE
Seventh Star Piece is Missing

### ISSUE THREAD

**Issue by MMildew** [DorkmasterFlek/smrpg_web_randomizer#91]
Emulator: Snes9x 1.60 x64

Were you using Crowd Control: Nah

Flags (paste flag string if available): 
Ksb R7kc Cspjl -nfc Yb -palette Tc4 M1 Sc4 Edfsac! Bmcs Qsba! X2 Nbmq D6s -showequips

Seed number or hash (seed number or hash string from filename or download page): SMRPG_US_8.2.9_open_529291eb400c06795c36b77d4943db40_4217706834

Description of problem: 
Can't access Smithy's Factory with R7 flag on despite beating every available boss and having gotten the star piece at Star Hill.

**Comment by DorkmasterFlek** [comment]
Your star piece locations (bosses in those locations vary) in this seed are: Belome 1, Box Boy, Dodo, Hidon, Mack, Punchinello, and Star Hill.  I don't know which one you missed, but all seven are there.  You may have missed one of the chest boss locations as those are optional fights normally and a lot of people forget about them.
