### ISSUE TITLE
Odd glitch, with invisible person behind house in Mushroom Kingdom

### ISSUE THREAD

**Issue by particalman1016** [DorkmasterFlek/smrpg_web_randomizer#97]
I have no idea if you are aware of this or not, but whenever I play a randomized game, and I go near the place where it is, the screen starts glitching out and lagging until I get far enough away.

**Comment by DorkmasterFlek** [comment]
This is a known bug with a missing event, probably related to the Peach parasol cutscene.  The workaround is just don't go behind that house for now.  This should be fixed in the revamp that's currently in the works.
