### ISSUE TITLE
smrpg rando bug Johnny Freeze

### ISSUE THREAD

**Issue by TastySeaSponge** [DorkmasterFlek/smrpg_web_randomizer#99]
PLEASE DO NOT USE THIS FORM TO REQUEST FEATURES!  THIS IS FOR BUG REPORTS ONLY!
If you wish to discuss new features, please join our Discord server: http://discord.smrpgspeedruns.com

Console or Emulator: 
Emulator 
 If emulator state which emulator and version.  If console, state which flash cart firmware.
snes9x 1.60
Were you using Crowd Control:
no
 NOTE: Crowd Control is NOT officially supported for the randomizer currently.  Please ONLY report issues if they are happening WITHOUT Crowd Control!  See https://forum.warp.world/t/super-mario-rpg-legend-of-the-seven-stars-snes/14219 for details.

Flags (paste flag string if available): 
Ks R Csjl -nfc -palette Tc4y $ M2 Sb4 Ed Bm Qa X3 P1 Nbmq D2s W -showequips 
Seed number or hash (seed number or hash string from filename or download page): 
SMRPG_US_8.2.9_open_7198a286fff420d17458dbcde2aacf63_305021658
Permalink (permalink URL from download page if you have it): 

Description of problem: 
Johnny boss at Bundt slot freezes when he goes to 1v1 mario. I tried with Mario in all 3 slots

**Comment by pidgezero-one** [comment]
Did you use Lamb's Lure or Sheep Attack on any of the bandana blues?

**Comment by TastySeaSponge** [comment]
Yes, I used Sheep Attack. I just checked without using it and it worked just fine, thanks for the help

**Comment by pidgezero-one** [comment]
No problem! The event code for the 1-on-1 attempts to re-summon two Bandana Blues, so if they were removed irregularly (like via the Lamb's Lure, which you don't normally have access to before Seaside in the original game) the game doesn't know what to do and crashes.

That bug has a complicated fix, but it will be fixed when the next patch is released, so once that happens you can safely use those items on that fight.
